---
abstract: 'Base classes wrapping fundamental Perl data types.'
author:
  - 'Matthew Phillips <mattp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Perl
requires:
  strictures: 0
resources:
  repository: git://github.com/mattp-/Data-Perl.git
version: 0.001002
